# Generated by Django 6.0.5 on 2026-10-02 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosen',
            options={'verbose_name': 'Dosen', 'verbose_name_plural': 'Dosen'},
        ),
        migrations.AlterModelOptions(
            name='jadwal',
            options={'verbose_name': 'Jadwal', 'verbose_name_plural': 'Jadwal'},
        ),
        migrations.AlterModelOptions(
            name='kelas',
            options={'verbose_name': 'Kelas', 'verbose_name_plural': 'Kelas'},
        ),
        migrations.AlterModelOptions(
            name='mahasiswa',
            options={'verbose_name': 'Mahasiswa', 'verbose_name_plural': 'Mahasiswa'},
        ),
        migrations.AlterModelOptions(
            name='matakuliah',
            options={'verbose_name': 'Mata Kuliah', 'verbose_name_plural': 'Mata Kuliah'},
        ),
        migrations.RenameField(
            model_name='dosen',
            old_name='nip',
            new_name='nidn',
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='kelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kelas'),
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('tanggal_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tanggal_diperbarui', models.DateTimeField(auto_now=True)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_embedding', to='core.mahasiswa')),
            ],
            options={
                'verbose_name': 'Face Embedding',
                'verbose_name_plural': 'Face Embedding',
            },
        ),
    ]
