# Generated by Django 6.0.5 on 2026-10-02 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dosen_options_alter_jadwal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesiAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_buka', models.DateTimeField()),
                ('waktu_tutup', models.DateTimeField()),
                ('aktif', models.BooleanField(default=False)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesi_absensi', to='core.jadwal')),
            ],
            options={
                'verbose_name': 'Sesi Absensi',
                'verbose_name_plural': 'Sesi Absensi',
            },
        ),
        migrations.CreateModel(
            name='RiwayatAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_absen', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('HADIR', 'Hadir'), ('TERLAMBAT', 'Terlambat')], default='HADIR', max_length=20)),
                ('distance_score', models.FloatField(blank=True, null=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_absensi', to='core.mahasiswa')),
                ('sesi_absensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_absensi', to='core.sesiabsensi')),
            ],
            options={
                'verbose_name': 'Riwayat Absensi',
                'verbose_name_plural': 'Riwayat Absensi',
            },
        ),
    ]
